apiVersion: apps/v1
kind: Deployment
metadata:
  name: authmgmt
  labels:
    app: authmgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authmgmt
  template:
    metadata:
      labels:
        app: authmgmt
    spec:
      containers:
      - name: authmgmt
        image: taxi/authmgmt
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
              
---
apiVersion: v1
kind: Service
metadata:
  name: authmgmt-service
spec:
  selector:
    app: authmgmt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
