apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt
  labels:
    app: usermgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt
  template:
    metadata:
      labels:
        app: usermgmt
    spec:
      containers:
      - name: usermgmt
        image: taxi/usermgmt
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgresql-configmap
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: pg_db
---
apiVersion: v1
kind: Service
metadata:
  name: usermgmt-service
spec:
  selector:
    app: usermgmt
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
