apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt
  labels:
    app: usermgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt
  template:
    metadata:
      labels:
        app: usermgmt
    spec:
      containers:
      - name: usermgmt
        image: taxi/usermgmt
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
              
---
apiVersion: v1
kind: Service
metadata:
  name: usermgmt-service
spec:
  selector:
    app: usermgmt
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
