apiVersion: apps/v1
kind: Deployment
metadata:
  name: callcenter
  labels:
    app: callcenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callcenter
  template:
    metadata:
      labels:
        app: callcenter
    spec:
      containers:
      - name: callcenter
        image: minhthao56/callcenter
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: twilio-config
              key: sid
        - name: REACT_APP_TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: twilio-config
              key: token
        - name: REACT_APP_BASE_URL
          valueFrom:
            secretKeyRef:
              name: call-center-config
              key: base_url
        - name: REACT_APP_TWILIO_BASE_URL
          valueFrom:
            secretKeyRef:
              name: call-center-config
              key: base_url
        - name: REACT_APP_PUBLIC_GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: map-config
              key: google_token
        - name: REACT_APP_GOONG_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: map-config
              key: goong_token
              
---
apiVersion: v1
kind: Service
metadata:
  name: callcenter-service
spec:
  selector:
    app: callcenter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
