[package]
name = "authmgmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { workspace = true}
reqwest = { workspace = true}

[[bin]]
name = "authmgmt"
path = "src/main.rs"