apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking
        image: taxi/booking
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6060
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgresql-configmap
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: pg_db
              
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
