apiVersion: apps/v1
kind: Deployment
metadata:
  name: communicate
  labels:
    app: communicate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communicate
  template:
    metadata:
      labels:
        app: communicate
    spec:
      containers:
      - name: communicate
        image: minhthao56/communicate
        imagePullPolicy: Always
        volumeMounts:
        - name: firebase-config
          mountPath: /firebase
          readOnly: true
        ports:
        - containerPort: 7070
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: postgresql-configmap
              key: db_host
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: pg_db
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: twilio-config
              key: sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: twilio-config
              key: token
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: twilio-config
              key: phone
      volumes:
      - name: firebase-config
        secret:
          secretName: firebase-config
              
---
apiVersion: v1
kind: Service
metadata:
  name: communicate-service
spec:
  selector:
    app: communicate
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
